import { useState, useCallback } from 'react';

// Define translations
const translations = {
  en: {
    app_title: 'Lian Studio',
    back_to_home: 'Back to Home',
    landing_title: 'Unleash Your Creativity with AI',
    landing_subtitle: 'Generate, enhance, merge, and extract from images using the power of Gemini. A new era of digital artistry awaits.',
    editor_card_title: 'Editor',
    editor_card_desc: 'Precisely edit parts of an image using masks and prompts. Change colors, add objects, or remove imperfections with fine-tuned control.',
    start_editing: 'Start Editing',
    generator_card_title: 'Generator',
    generator_card_desc: 'Create unique images from text prompts and reference photos. Your imagination is the only limit.',
    start_generating: 'Start Generating',
    enhancer_card_title: 'Enhancer',
    enhancer_card_desc: 'Refine and upscale your images. Add details, fix imperfections, or change styles with a simple prompt.',
    start_enhancing: 'Start Enhancing',
    merger_card_title: 'Merger',
    merger_card_desc: 'Combine multiple images into a single, coherent masterpiece. Blend styles, subjects, and scenes effortlessly.',
    start_merging: 'Start Merging',
    extractor_card_title: 'Extractor',
    extractor_card_desc: 'Pull out the exact prompt used to create an image. Understand the art behind the visuals.',
    start_extracting: 'Start Extracting',
    beta_tag: 'Beta',
    landing_about_title: 'About Lian Studio',
    landing_about_desc: 'Lian Studio is a powerful suite of AI-powered tools designed to revolutionize your creative workflow. Built on Google\'s Gemini, it offers state-of-the-art image generation and manipulation capabilities in an intuitive interface.',
    landing_importance_title: 'Why It Matters',
    landing_importance_desc: 'In a world driven by visual content, the ability to quickly create and modify high-quality images is crucial. Lian Studio empowers creators of all skill levels to bring their visions to life, saving time and unlocking new creative possibilities.',
    landing_goals_title: 'Our Goal',
    landing_goals_desc: 'Our mission is to make advanced AI technology accessible and easy to use. We aim to provide a seamless experience that inspires creativity and helps you produce stunning visuals for any purpose.',
    landing_features_title: 'Core Features',
    landing_feature_1_title: 'Advanced Image Generation',
    landing_feature_1_desc: 'Utilize text and image prompts to generate high-fidelity images in various styles and aspect ratios.',
    landing_feature_2_title: 'Intelligent Image Enhancement',
    landing_feature_2_desc: 'Improve resolution, add details, and apply stylistic changes to existing images with precision.',
    landing_feature_3_title: 'Seamless Image Merging',
    landing_feature_3_desc: 'Combine elements from up to 15 different images into one harmonious composition.',
    landing_feature_4_title: 'Prompt Extraction',
    landing_feature_4_desc: 'Discover the prompts behind any image, providing insight and inspiration for your own creations.',
    landing_feature_5_title: 'Precision Editing',
    landing_feature_5_desc: 'Isolate and modify specific parts of an image by drawing a mask, offering unparalleled control over your creations.',
    toggle_theme_dark: 'Switch to dark mode',
    toggle_theme_light: 'Switch to light mode',
    switch_language_to_ar: 'Switch to Arabic',
    switch_language_to_en: 'Switch to English',
    api_key_tooltip: 'Manage API Key',
    generator_title: 'Image Generator',
    prompt_label: 'Prompt',
    upload_prompt_label: 'Upload prompt from .txt file',
    prompt_placeholder: 'e.g., A surreal painting of a cat playing a cello in a forest at night...',
    reference_images_label: 'Reference Images (Optional)',
    reference_images_desc: 'Add up to 5 images to guide the generation. Supported formats: PNG, JPG, WEBP. Max 10MB each.',
    aspect_ratio_label: 'Aspect Ratio',
    aspect_ratio_Default: 'Default',
    aspect_ratio_Square: 'Square',
    aspect_ratio_Portrait: 'Portrait',
    aspect_ratio_Landscape: 'Landscape',
    quality_label: 'Quality',
    quality_Standard: 'Standard',
    quality_HD: 'HD',
    generate_button: 'Generate',
    generating_title: 'Generating Image...',
    generating_desc: 'The AI is working its magic. This may take a moment.',
    enhancing_title: 'Enhancing Image...',
    enhancing_desc: 'Applying enhancements. This should be quick.',
    merging_title: 'Merging Images...',
    merging_desc: 'Combining your images. This might take a little while.',
    editing_title: 'Editing Image...',
    editing_desc: 'The AI is applying your edits. This may take a moment.',
    error_title: 'An Error Occurred',
    generated_image_alt: 'Generated image result',
    download_image_label: 'Download Image',
    initial_title: 'Your result will appear here',
    initial_desc: 'Enter your prompt and settings, then click "Generate".',
    initial_desc_extractor: 'Upload an image and the extracted prompt will appear here.',
    enhancer_title: 'Image Enhancer',
    base_image_label: 'Base Image',
    base_image_desc: 'Upload a single image to enhance. Supported formats: PNG, JPG, WEBP.',
    base_image_desc_editor: 'Upload a single image to edit. Supported formats: PNG, JPG, WEBP.',
    enhancement_label: 'Enhancement Prompt',
    enhancement_placeholder: 'e.g., Increase resolution, add cinematic lighting, make it look like an oil painting...',
    enhancement_strength: 'Enhancement Strength',
    enhance_button: 'Enhance',
    editor_title: 'Image Editor',
    edit_instructions_label: 'Edit Instructions',
    edit_instructions_placeholder: 'e.g., Change the color of the masked area to royal blue...',
    mask_area_label: 'Mask Area to Edit',
    mask_area_desc: 'Use the brush to draw over the parts of the image you want to change.',
    brush_size: 'Brush Size',
    mask_color: 'Mask Color',
    clear_mask: 'Clear Mask',
    undo_mask: 'Undo Last Stroke',
    edit_button: 'Edit Image',
    extractor_title: 'Prompt Extractor',
    base_image_label_extractor: 'Image to Extract From',
    base_image_desc_extractor: 'Upload the image you want to analyze.',
    output_language_label: 'Output Language',
    output_language_en: 'English',
    output_language_ar: 'Arabic',
    output_language_es: 'Spanish',
    output_language_fr: 'French',
    output_language_de: 'German',
    output_language_ja: 'Japanese',
    extract_button: 'Extract Prompt',
    extracting_title: 'Extracting Prompt...',
    extracting_desc: 'Analyzing the image to uncover its prompt.',
    copy_success: 'Copied!',
    copy_button: 'Copy to clipboard',
    download_prompt_label: 'Download prompt as .txt file',
    image_preview_title: 'Image Preview',
    close_preview: 'Close preview',
    uploader_cta: 'Click to upload or drag and drop',
    uploader_cta_add_more: 'Add more',
    uploader_error_size: 'File is too large. Max size is 10MB.',
    uploader_error_type: 'Invalid file type. Please use PNG, JPG, or WEBP.',
    uploader_error_count: 'You can upload a maximum of 5 images.',
    uploader_error_single_count: 'You can only upload a single image.',
    uploader_error_merge_count: 'You can upload a maximum of 15 images for merging.',
    merger_title: 'Image Merger',
    source_images_label: 'Source Images',
    source_images_desc: 'Upload 2 to 15 images to merge.',
    merger_prompt_label: 'Merge Instructions (Optional)',
    merger_prompt_placeholder: 'e.g., Combine these images into a fantasy landscape. Use the castle from image 1 and the dragon from image 2...',
    merge_button: 'Merge',
    api_key_modal_title_manual: 'Your Gemini API Key',
    api_key_modal_desc_manual: 'Your key is stored securely in your browser\'s local storage and is never sent to our servers. This allows you to use your own models and quotas.',
    api_key_input_placeholder: 'Enter your Gemini API key',
    api_key_save_button: 'Save Key',
    api_key_close_button: 'Close',
    show_api_key: 'Show API key',
    hide_api_key: 'Hide API key',
    api_key_validating: 'Validating...',
    api_key_valid: 'Key is valid',
    api_key_invalid: 'Invalid API key',
  },
  ar: {
    app_title: 'استوديو ليان',
    back_to_home: 'العودة للرئيسية',
    landing_title: 'أطلق العنان لإبداعك مع الذكاء الاصطناعي',
    landing_subtitle: 'أنشئ، حسّن، ادمج، واستخرج من الصور باستخدام قوة Gemini. عصر جديد من الفن الرقمي ينتظرك.',
    editor_card_title: 'المحرر',
    editor_card_desc: 'حرر أجزاء من الصورة بدقة باستخدام الأقنعة والأوامر. غيّر الألوان، أضف عناصر، أو أزل العيوب.',
    start_editing: 'ابدأ التحرير',
    generator_card_title: 'المولّد',
    generator_card_desc: 'ابتكر صورًا فريدة من النصوص والصور المرجعية. خيالك هو الحد الوحيد.',
    start_generating: 'ابدأ الإنشاء',
    enhancer_card_title: 'المحسّن',
    enhancer_card_desc: 'صقل صورك وحسّن جودتها. أضف تفاصيل، أصلح العيوب، أو غيّر الأنماط بأمر بسيط.',
    start_enhancing: 'ابدأ التحسين',
    merger_card_title: 'الدامج',
    merger_card_desc: 'اجمع عدة صور في تحفة فنية واحدة متماسكة. امزج الأساليب والمواضيع والمشاهد بسهولة.',
    start_merging: 'ابدأ الدمج',
    extractor_card_title: 'المستخرج',
    extractor_card_desc: 'استخرج النص الدقيق المستخدم لإنشاء صورة. افهم الفن وراء المرئيات.',
    start_extracting: 'ابدأ الاستخراج',
    beta_tag: 'تجريبي',
    landing_about_title: 'عن استوديو ليان',
    landing_about_desc: 'استوديو ليان هو مجموعة قوية من الأدوات المدعومة بالذكاء الاصطناعي مصممة لإحداث ثورة في سير عملك الإبداعي. مبني على Gemini من Google، ويقدم أحدث إمكانيات إنشاء الصور ومعالجتها في واجهة سهلة الاستخدام.',
    landing_importance_title: 'لماذا هو مهم',
    landing_importance_desc: 'في عالم يحركه المحتوى المرئي، تعد القدرة على إنشاء وتعديل صور عالية الجودة بسرعة أمرًا بالغ الأهمية. يمكّن استوديو ليان المبدعين من جميع مستويات المهارة من تحقيق رؤاهم، مما يوفر الوقت ويفتح إمكانيات إبداعية جديدة.',
    landing_goals_title: 'هدفنا',
    landing_goals_desc: 'مهمتنا هي جعل تكنولوجيا الذكاء الاصطناعي المتقدمة متاحة وسهلة الاستخدام. نهدف إلى توفير تجربة سلسة تلهم الإبداع وتساعدك على إنتاج مرئيات مذهلة لأي غرض.',
    landing_features_title: 'الميزات الأساسية',
    landing_feature_1_title: 'إنشاء صور متقدم',
    landing_feature_1_desc: 'استخدم النصوص والصور لإنشاء صور عالية الدقة بأنماط ونسب أبعاد مختلفة.',
    landing_feature_2_title: 'تحسين ذكي للصور',
    landing_feature_2_desc: 'حسّن الدقة، وأضف التفاصيل، وطبّق تغييرات أسلوبية على الصور الموجودة بدقة.',
    landing_feature_3_title: 'دمج سلس للصور',
    landing_feature_3_desc: 'اجمع عناصر من ما يصل إلى 15 صورة مختلفة في تكوين واحد متناغم.',
    landing_feature_4_title: 'استخراج الأوامر النصية',
    landing_feature_4_desc: 'اكتشف الأوامر النصية وراء أي صورة، مما يوفر رؤية وإلهامًا لإبداعاتك الخاصة.',
    landing_feature_5_title: 'تحرير دقيق',
    landing_feature_5_desc: 'اعزل وعدّل أجزاء معينة من الصورة عن طريق رسم قناع، مما يوفر تحكمًا لا مثيل له في إبداعاتك.',
    toggle_theme_dark: 'التبديل إلى الوضع الداكن',
    toggle_theme_light: 'التبديل إلى الوضع الفاتح',
    switch_language_to_ar: 'التبديل إلى اللغة العربية',
    switch_language_to_en: 'التبديل إلى اللغة الإنجليزية',
    api_key_tooltip: 'إدارة مفتاح API',
    generator_title: 'مولّد الصور',
    prompt_label: 'الأمر النصي',
    upload_prompt_label: 'تحميل الأمر النصي من ملف .txt',
    prompt_placeholder: 'مثال: لوحة سريالية لقط يعزف على التشيلو في غابة ليلًا...',
    reference_images_label: 'صور مرجعية (اختياري)',
    reference_images_desc: 'أضف ما يصل إلى 5 صور لتوجيه الإنشاء. الصيغ المدعومة: PNG, JPG, WEBP. الحجم الأقصى 10 ميجابايت لكل منها.',
    aspect_ratio_label: 'نسبة الأبعاد',
    aspect_ratio_Default: 'افتراضي',
    aspect_ratio_Square: 'مربع',
    aspect_ratio_Portrait: 'عمودي',
    aspect_ratio_Landscape: 'أفقي',
    quality_label: 'الجودة',
    quality_Standard: 'قياسية',
    quality_HD: 'عالية الدقة',
    generate_button: 'إنشاء',
    generating_title: 'جاري إنشاء الصورة...',
    generating_desc: 'الذكاء الاصطناعي يعمل بسحره. قد يستغرق هذا بعض الوقت.',
    enhancing_title: 'جاري تحسين الصورة...',
    enhancing_desc: 'تطبيق التحسينات. يجب أن يكون هذا سريعًا.',
    merging_title: 'جاري دمج الصور...',
    merging_desc: 'دمج صورك. قد يستغرق هذا بعض الوقت.',
    editing_title: 'جاري تحرير الصورة...',
    editing_desc: 'يقوم الذكاء الاصطناعي بتطبيق تعديلاتك. قد يستغرق هذا بعض الوقت.',
    error_title: 'حدث خطأ',
    generated_image_alt: 'نتيجة الصورة المُنشأة',
    download_image_label: 'تنزيل الصورة',
    initial_title: 'ستظهر نتيجتك هنا',
    initial_desc: 'أدخل الأمر النصي والإعدادات، ثم انقر على "إنشاء".',
    initial_desc_extractor: 'قم بتحميل صورة وسيظهر النص المستخرج هنا.',
    enhancer_title: 'محسّن الصور',
    base_image_label: 'الصورة الأساسية',
    base_image_desc: 'قم بتحميل صورة واحدة لتحسينها. الصيغ المدعومة: PNG, JPG, WEBP.',
    base_image_desc_editor: 'قم بتحميل صورة واحدة لتحريرها. الصيغ المدعومة: PNG, JPG, WEBP.',
    enhancement_label: 'أمر التحسين',
    enhancement_placeholder: 'مثال: زيادة الدقة، إضافة إضاءة سينمائية، جعلها تبدو كلوحة زيتية...',
    enhancement_strength: 'قوة التحسين',
    enhance_button: 'تحسين',
    editor_title: 'محرر الصور',
    edit_instructions_label: 'تعليمات التحرير',
    edit_instructions_placeholder: 'مثال: غير لون المنطقة المحددة إلى الأزرق الملكي...',
    mask_area_label: 'منطقة التحرير',
    mask_area_desc: 'استخدم الفرشاة للرسم فوق أجزاء الصورة التي تريد تغييرها.',
    brush_size: 'حجم الفرشاة',
    mask_color: 'لون القناع',
    clear_mask: 'مسح القناع',
    undo_mask: 'التراجع عن آخر خطوة',
    edit_button: 'تحرير الصورة',
    extractor_title: 'مستخرج الأوامر',
    base_image_label_extractor: 'صورة لاستخراج النص منها',
    base_image_desc_extractor: 'قم بتحميل الصورة التي تريد تحليلها.',
    output_language_label: 'لغة الإخراج',
    output_language_en: 'الإنجليزية',
    output_language_ar: 'العربية',
    output_language_es: 'الإسبانية',
    output_language_fr: 'الفرنسية',
    output_language_de: 'الألمانية',
    output_language_ja: 'اليابانية',
    extract_button: 'استخراج الأمر',
    extracting_title: 'جاري استخراج الأمر...',
    extracting_desc: 'تحليل الصورة للكشف عن الأمر النصي الخاص بها.',
    copy_success: 'تم النسخ!',
    copy_button: 'نسخ إلى الحافظة',
    download_prompt_label: 'تنزيل الأمر كملف .txt',
    image_preview_title: 'معاينة الصورة',
    close_preview: 'إغلاق المعاينة',
    uploader_cta: 'انقر للتحميل أو اسحب وأفلت',
    uploader_cta_add_more: 'إضافة المزيد',
    uploader_error_size: 'الملف كبير جدًا. الحجم الأقصى هو 10 ميجابايت.',
    uploader_error_type: 'نوع ملف غير صالح. يرجى استخدام PNG أو JPG أو WEBP.',
    uploader_error_count: 'يمكنك تحميل 5 صور كحد أقصى.',
    uploader_error_single_count: 'يمكنك تحميل صورة واحدة فقط.',
    uploader_error_merge_count: 'يمكنك تحميل 15 صورة كحد أقصى للدمج.',
    merger_title: 'دامج الصور',
    source_images_label: 'الصور المصدر',
    source_images_desc: 'قم بتحميل من 2 إلى 15 صورة لدمجها.',
    merger_prompt_label: 'تعليمات الدمج (اختياري)',
    merger_prompt_placeholder: 'مثال: ادمج هذه الصور في مشهد خيالي. استخدم القلعة من الصورة 1 والتنين من الصورة 2...',
    merge_button: 'دمج',
    api_key_modal_title_manual: 'مفتاح Gemini API الخاص بك',
    api_key_modal_desc_manual: 'يتم تخزين مفتاحك بشكل آمن في التخزين المحلي للمتصفح ولا يتم إرساله أبدًا إلى خوادمنا. يتيح لك هذا استخدام النماذج والحصص الخاصة بك.',
    api_key_input_placeholder: 'أدخل مفتاح Gemini API الخاص بك',
    api_key_save_button: 'حفظ المفتاح',
    api_key_close_button: 'إغلاق',
    show_api_key: 'إظهار مفتاح API',
    hide_api_key: 'إخفاء مفتاح API',
    api_key_validating: 'جاري التحقق...',
    api_key_valid: 'المفتاح صالح',
    api_key_invalid: 'مفتاح API غير صالح',
  },
};

export type Language = 'en' | 'ar';
export type TFunction = (key: keyof typeof translations.en) => string;
type Direction = 'ltr' | 'rtl';

export const useLocalization = () => {
  const [language, setLanguage] = useState<Language>('en');

  const setLang = useCallback((lang: Language) => {
    setLanguage(lang);
  }, []);

  const t = useCallback((key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key];
  }, [language]);
  
  const dir: Direction = language === 'ar' ? 'rtl' : 'ltr';

  return { t, setLanguage: setLang, language, dir };
};