
import { useState, useCallback } from 'react';

// Define translations
const translations = {
  en: {
    app_title: 'Lian Studio',
    back_to_home: 'Back to Home',
    landing_title: 'Unleash Your Creativity with AI',
    landing_subtitle: 'Create, enhance, and produce across images, video, audio, and text using the power of Gemini. Your complete creative studio awaits.',
    content_type_images: 'Images',
    content_type_videos: 'Videos',
    content_type_audio: 'Audio',
    content_type_text: 'Text',
    coming_soon_title: 'Coming Soon!',
    coming_soon_desc: 'This section is under development. Stay tuned for exciting new features!',
    editor_card_title: 'Editor',
    editor_card_desc: 'Precisely edit parts of an image using masks and prompts. Change colors, add objects, or remove imperfections with fine-tuned control.',
    start_editing: 'Start Editing',
    generator_card_title: 'Generator',
    generator_card_desc: 'Create unique images from text prompts and reference photos. Your imagination is the only limit.',
    start_generating: 'Start Generating',
    enhancer_card_title: 'Enhancer',
    enhancer_card_desc: 'Refine and upscale your images. Add details, fix imperfections, or change styles with a simple prompt.',
    start_enhancing: 'Start Enhancing',
    restorer_card_title: 'Restorer',
    restorer_card_desc: 'Restore, colorize, and enhance old photos while preserving all elements and details.',
    start_restoring: 'Start Restoring',
    merger_card_title: 'Merger',
    merger_card_desc: 'Combine multiple images into a single, coherent masterpiece. Blend styles, subjects, and scenes effortlessly.',
    start_merging: 'Start Merging',
    extractor_card_title: 'Extractor',
    extractor_card_desc: 'Pull out the exact prompt used to create an image. Understand the art behind the visuals.',
    start_extracting: 'Start Extracing',
    corrector_card_title: 'Corrector',
    corrector_card_desc: 'Refine your simple ideas into detailed, professional prompts for the AI. Multilingual support.',
    start_correcting: 'Start Correcting',
    writer_card_title: 'Writer',
    writer_card_desc: 'Generate marketing copy, social media posts, and more from a simple description and optional product image.',
    start_writing: 'Start Writing',
    translator_card_title: 'Translator',
    translator_card_desc: 'Translate text and documents with high accuracy across multiple languages, featuring auto-detection.',
    start_translating: 'Start Translating',
    proofreader_card_title: 'Proofreader',
    proofreader_card_desc: 'Check for spelling and grammatical errors, improve text quality, and ensure your writing is flawless. Supports multiple languages.',
    start_proofreading: 'Start Proofreading',
    stealth_card_title: 'Stealth',
    stealth_card_desc: 'Rewrite AI-generated text to appear human-written and avoid detection.',
    start_stealthing: 'Start Stealthing',
    beta_tag: 'Beta',
    info_tab_about: 'About',
    info_tab_why: 'Why Us?',
    info_tab_mission: 'Mission',
    info_tab_features: 'Features',
    landing_about_title: 'About Lian Studio',
    landing_about_desc: "Lian Studio is your all-in-one creative hub, powered by the latest AI from Gemini. We provide an integrated suite of tools for images, videos, audio, and text, designed to be your partner at every stage of the creative process—from initial concept to polished final product.",
    landing_importance_title: 'Why Lian Studio?',
    landing_importance_desc: "In a world driven by compelling digital content, the ability to effortlessly transform ideas into professional-quality media is essential. Lian Studio removes technical barriers, empowering every creator—from professionals to hobbyists—to bring their vision to life across any medium with unparalleled ease and precision.",
    landing_goals_title: 'Our Mission',
    landing_goals_desc: "Our mission is to democratize creativity by placing the most advanced multi-modal AI technologies at your fingertips through a simple, elegant interface. We strive to be the spark that inspires creators to produce exceptional works that leave a lasting, unforgettable impact.",
    landing_features_title: 'Core Features',
    landing_feature_1_title: 'Advanced Image Generation',
    landing_feature_1_desc: 'Utilize text and image prompts to generate high-fidelity images in various styles and aspect ratios.',
    landing_feature_2_title: 'Intelligent Image Enhancement',
    landing_feature_2_desc: 'Improve resolution, add details, and apply stylistic changes to existing images with precision.',
    landing_feature_3_title: 'Seamless Image Merging',
    landing_feature_3_desc: 'Combine elements from up to 15 different images into one harmonious composition.',
    landing_feature_4_title: 'Prompt Extraction',
    landing_feature_4_desc: 'Discover the prompts behind any image, providing insight and inspiration for your own creations.',
    landing_feature_5_title: 'Precision Editing',
    landing_feature_5_desc: 'Isolate and modify specific parts of an image by drawing a mask, offering unparalleled control over your creations.',
    landing_feature_6_title: 'Prompt Correction',
    landing_feature_6_desc: 'Transform simple ideas into detailed, high-quality prompts ready for AI generation, with multilingual support.',
    landing_feature_7_title: 'Intelligent Photo Restoration',
    landing_feature_7_desc: 'Automatically repair, colorize, and enhance old or damaged photos with a single click.',
    landing_feature_8_title: 'Dynamic Video Generation (Coming Soon)',
    landing_feature_8_desc: 'Create and edit stunning videos from text prompts, images, or existing clips.',
    landing_feature_9_title: 'Intelligent Audio Production (Coming Soon)',
    landing_feature_9_desc: 'Generate high-quality voiceovers, music, and sound effects with simple commands.',
    landing_feature_10_title: 'Advanced Text & Content Tools (Coming Soon)',
    landing_feature_10_desc: 'Craft, summarize, and translate compelling written content for any purpose.',
    landing_feature_11_title: 'Content Writer',
    landing_feature_11_desc: 'Generate marketing copy, social media posts, and more from a simple description and optional product image.',
    landing_feature_12_title: 'AI Translator',
    landing_feature_12_desc: 'Translate text with high accuracy across multiple languages, featuring auto-detection and formality controls.',
    toggle_theme_dark: 'Switch to dark mode',
    toggle_theme_light: 'Switch to light mode',
    switch_language_to_ar: 'Switch to Arabic',
    switch_language_to_en: 'Switch to English',
    api_key_tooltip: 'Manage API Key',
    generator_title: 'Image Generator',
    prompt_label: 'Prompt',
    prompt_wave_tooltip: 'Get a random prompt',
    upload_prompt_label: 'Upload prompt from file',
    paste_from_clipboard: 'Paste from clipboard',
    paste_error_not_text: 'Clipboard content is not text.',
    prompt_placeholder: 'e.g., A surreal painting of a cat playing a cello in a forest at night...',
    reference_images_label: 'Reference Images (Optional)',
    reference_images_desc: 'Add up to 5 images to guide the generation. Supported formats: PNG, JPG, WEBP. Max 10MB each.',
    aspect_ratio_label: 'Aspect Ratio',
    aspect_ratio_Default: 'Default',
    aspect_ratio_Square: 'Square',
    aspect_ratio_Portrait: 'Portrait',
    aspect_ratio_Landscape: 'Landscape',
    quality_label: 'Quality',
    quality_Standard: 'Standard',
    quality_HD: 'HD',
    generate_button: 'Generate',
    generating_title: 'Generating Image...',
    generating_desc: 'The AI is working its magic. This may take a moment.',
    enhancing_title: 'Enhancing Image...',
    enhancing_desc: 'Applying enhancements. This should be quick.',
    merging_title: 'Merging Images...',
    merging_desc: 'Combining your images. This might take a little while.',
    editing_title: 'Editing Image...',
    editing_desc: 'The AI is applying your edits. This may take a moment.',
    restoring_title: 'Restoring Image...',
    restoring_desc: 'The AI is carefully restoring your photo. This might take some time.',
    error_title: 'An Error Occurred',
    generated_image_alt: 'Generated image result',
    download_image_label: 'Download Image',
    initial_title: 'Your result will appear here',
    initial_desc: 'Enter your prompt and settings, then click "Generate".',
    initial_desc_restorer: 'Upload a damaged or old photo to begin the restoration process.',
    initial_desc_extractor: 'Upload an image and the extracted prompt will appear here.',
    initial_desc_corrector: 'Write your idea and the refined prompt will appear here.',
    initial_desc_writer: 'Describe your product or idea to generate content.',
    initial_desc_translator: 'Enter text, select languages, and the translation will appear here.',
    initial_desc_proofreader: 'Enter your text and the corrected version will appear here.',
    initial_desc_stealth: 'Enter your AI-generated text and the humanized version will appear here.',
    enhancer_title: 'Image Enhancer',
    restorer_title: 'Image Restorer',
    base_image_label: 'Base Image',
    base_image_desc: 'Upload a single image to enhance. Supported formats: PNG, JPG, WEBP.',
    base_image_desc_editor: 'Upload a single image to edit. Supported formats: PNG, JPG, WEBP.',
    base_image_desc_restorer: 'Upload a single old or damaged photo to restore. Supported formats: PNG, JPG, WEBP.',
    restorer_options_label: 'Restoration Options',
    restorer_advanced_options_toggle: 'Advanced Options',
    restorer_option_fix_damage: 'Fix Scratches & Tears',
    restorer_option_improve_clarity: 'Improve Clarity',
    restorer_option_colorize: 'Colorize Photo',
    restorer_option_remove_noise: 'Remove Noise',
    restorer_instructions_label: 'Additional Instructions (Optional)',
    restorer_instructions_placeholder: 'e.g., Focus on restoring the faces, make the sky blue...',
    enhancement_label: 'Enhancement Prompt',
    enhancement_placeholder: 'e.g., Increase resolution, add cinematic lighting, make it look like an oil painting...',
    enhancement_strength: 'Enhancement Strength',
    enhance_button: 'Enhance',
    restore_button: 'Restore',
    editor_title: 'Image Editor',
    edit_instructions_label: 'General Edit Instructions',
    edit_instructions_placeholder: 'e.g., Make the overall image look more cinematic, add a soft focus...',
    color_prompt_placeholder: 'e.g., turn this part into red bricks',
    mask_area_label: 'Mask Area to Edit',
    mask_area_desc: 'Use the brush to draw over the parts of the image you want to change.',
    brush_size: 'Brush Size',
    mask_color: 'Mask Color',
    clear_mask: 'Clear Mask',
    undo_mask: 'Undo Last Stroke',
    redo_mask: 'Redo Last Stroke',
    edit_button: 'Edit Image',
    reset_view: 'Reset View',
    tool_brush: 'Brush',
    tool_eraser: 'Eraser',
    tool_pan: 'Pan Tool',
    toggle_mask_visibility: 'Toggle mask visibility',
    editor_pan_instruction: 'Use mouse wheel to zoom, hold Space and drag to pan.',
    zoom_tool: 'Zoom Tool',
    allow_shrinking: 'Allow shrinking',
    allow_zooming: 'Enable Zoom',
    extractor_title: 'Prompt Extractor',
    base_image_label_extractor: 'Image to Extract From',
    base_image_desc_extractor: 'Upload the image you want to analyze.',
    extraction_mode_label: 'Extraction Mode',
    extraction_mode_descriptive: 'Descriptive',
    extraction_mode_concise: 'Concise',
    output_language_label: 'Output Language',
    output_language_auto: 'Auto-detect',
    output_language_en: 'English',
    output_language_ar: 'Arabic',
    output_language_es: 'Spanish',
    output_language_fr: 'French',
    output_language_de: 'German',
    output_language_ja: 'Japanese',
    output_language_zh: 'Chinese',
    output_language_ru: 'Russian',
    output_language_hi: 'Hindi',
    extract_button: 'Extract Prompt',
    extracting_title: 'Extracting Prompt...',
    extracting_desc: 'Analyzing the image to uncover its prompt.',
    corrector_title: 'Prompt Corrector',
    corrector_idea_label: 'Your Idea',
    corrector_idea_placeholder: 'e.g., a knight fighting a dragon in a crystal cave',
    correct_button: 'Correct Prompt',
    correcting_title: 'Correcting Prompt...',
    correcting_desc: 'The AI is refining your idea into a masterpiece prompt.',
    writer_title: 'Content Writer',
    writer_idea_label: 'Idea or Product Description',
    writer_idea_placeholder: 'e.g., A new brand of organic coffee, sourced from Ethiopia, with a smooth and rich flavor.',
    writer_optional_image_label: 'Product Image (Optional)',
    writer_optional_image_desc: 'Add up to 5 product images to guide content generation.',
    writer_advanced_options_toggle: 'Advanced Options',
    writer_ratio_label: 'Content Ratio',
    writer_tone_label: 'Content Tone',
    tone_professional: 'Professional',
    tone_casual: 'Casual',
    tone_enthusiastic: 'Enthusiastic',
    tone_humorous: 'Humorous',
    tone_academic: 'Academic',
    tone_creative: 'Creative',
    writer_content_type_label: 'Content Type',
    content_type_social_media: 'Social Media Post',
    content_type_product_desc: 'Product Description',
    content_type_blog_idea: 'Blog Post Idea',
    content_type_email: 'Marketing Email',
    generate_content_button: 'Generate Content',
    writing_title: 'Writing Content...',
    writing_desc: 'The AI is crafting your content. This may take a moment.',
    translator_title: 'Text Translator',
    translator_input_label: 'Text or File to Translate',
    translator_input_placeholder: 'Enter text here or upload a file...',
    translator_file_uploaded_label: 'File for translation:',
    translator_remove_file_tooltip: 'Remove file',
    translator_output_format_note: 'Note: Translated content from files will be provided as plain text.',
    translator_from_label: 'From',
    translator_to_label: 'To',
    swap_languages_tooltip: 'Swap languages',
    translator_advanced_options_toggle: 'Advanced Options',
    translator_accuracy_label: 'Translation Accuracy',
    formality_label: 'Formality',
    formality_default: 'Default',
    formality_formal: 'Formal',
    formality_informal: 'Informal',
    translate_button: 'Translate',
    translating_title: 'Translating...',
    translating_desc: 'The AI is translating your content. Please wait.',
    proofreader_title: 'Proofreader',
    proofreader_input_label: 'Text or File to Proofread',
    proofreader_input_placeholder: 'Enter text here or upload a file...',
    proofreader_file_uploaded_label: 'File for proofreading:',
    proofreader_remove_file_tooltip: 'Remove file',
    proofreader_output_format_note: 'Note: Corrected content from files will be provided as plain text.',
    proofread_button: 'Proofread',
    proofreading_title: 'Proofreading Text...',
    proofreading_desc: 'The AI is checking your text for errors and improvements.',
    proofreader_advanced_options_toggle: 'Advanced Options',
    correction_level_label: 'Correction Level',
    correction_level_basic: 'Basic',
    correction_level_advanced: 'Advanced',
    correction_level_rewrite: 'Rewrite',
    target_audience_label: 'Target Audience',
    audience_general: 'General',
    audience_academic: 'Academic',
    audience_business: 'Business',
    proofreader_vocalization_label: 'Vocalization',
    proofreader_grammar_discipline_label: 'Grammatical Discipline',
    stealth_title: 'Stealth',
    stealth_input_label: 'AI-Generated Text',
    stealth_input_placeholder: 'Paste your AI-generated text here...',
    stealth_advanced_options_toggle: 'Advanced Options',
    stealth_file_uploaded_label: 'File for humanization:',
    stealth_remove_file_tooltip: 'Remove file',
    stealth_output_format_note: 'Note: Humanized content from files will be provided as plain text.',
    rewrite_intensity_label: 'Rewrite Intensity',
    humanization_tone_label: 'Tone of Voice',
    complexity_level_label: 'Complexity Level',
    complexity_simple: 'Simple',
    complexity_standard: 'Standard',
    complexity_advanced: 'Advanced',
    humanization_techniques_label: 'Humanization Techniques',
    technique_anecdotes: 'Add personal anecdotes/idioms',
    technique_vary_structure: 'Vary sentence structure',
    technique_imperfections: 'Introduce slight imperfections',
    stealth_button: 'Humanize Text',
    stealthing_title: 'Humanizing Text...',
    stealthing_desc: 'The AI is working its magic to make the text sound more human.',
    copy_success: 'Copied!',
    copy_button: 'Copy to clipboard',
    download_prompt_label: 'Download as .txt file',
    image_preview_title: 'Image Preview',
    close_preview: 'Close preview',
    uploader_cta_title: 'Upload Images',
    uploader_cta_desc: 'Click to upload or drag & drop. Single or multiple files.',
    uploader_cta_desc_translator: 'Upload a .txt, .pdf, or .docx file.',
    uploader_cta_desc_stealth: 'Upload a .txt, .pdf, or .docx file.',
    uploader_cta_add_more: 'Add more',
    uploader_error_size: 'File is too large. Max size is 10MB.',
    uploader_error_type: 'Invalid file type. Please use PNG, JPG, or WEBP.',
    uploader_error_count: 'You can upload a maximum of 5 images.',
    uploader_error_single_count: 'You can only upload a single image.',
    uploader_error_merge_count: 'You can upload a maximum of 15 images for merging.',
    merger_title: 'Image Merger',
    source_images_label: 'Source Images',
    source_images_desc: 'Upload 2 to 15 images to merge.',
    merger_prompt_label: 'Merge Instructions (Optional)',
    merger_prompt_placeholder: 'e.g., Combine these images into a fantasy landscape. Use the castle from image 1 and the dragon from image 2...',
    merge_button: 'Merge',
    api_key_modal_title_manual: 'Your Gemini API Key',
    api_key_modal_desc_manual: 'Your key is stored securely in your browser\'s local storage and is never sent to our servers. This allows you to use your own models and quotas.',
    api_key_input_placeholder: 'Enter your Gemini API key',
    api_key_save_button: 'Save Key',
    api_key_close_button: 'Close',
    show_api_key: 'Show API key',
    hide_api_key: 'Hide API key',
    api_key_validating: 'Validating...',
    api_key_valid: 'Key is valid',
    api_key_invalid: 'Invalid API key',
    footer_text: 'Made with love',
    footer_copyright_brand: '© {year} Google\'s Gemini AI.',
    footer_copyright_legal: 'All rights reserved.',
    contact_us_tooltip: 'Contact Us',
    developer_modal_title: 'About the Developer',
    developer_label: 'Developer',
    developer_name: 'Salah Al-Din Mansour Al-Droubi',
    developer_bio: 'A developer with a background in graphic design, combining a passion for code with an eye for aesthetics to create innovative and beautiful digital experiences.',
    tooltip_facebook: 'Facebook',
    tooltip_instagram: 'Instagram',
    tooltip_x: 'X (Twitter)',
    tooltip_telegram: 'Telegram',
    tooltip_whatsapp: 'WhatsApp',
    tooltip_email: 'Email',
    tooltip_github: 'GitHub',
    collapse_toolbar: 'Collapse toolbar',
    expand_toolbar: 'Expand toolbar',
    prompts_label: 'Prompts',
    prompts_available_tooltip: '{count}+ Prompts Available',
  },
  ar: {
    app_title: 'استوديو ليان',
    back_to_home: 'العودة للرئيسية',
    landing_title: 'أطلق العنان لإبداعك مع الذكاء الاصطناعي',
    landing_subtitle: 'أنشئ، حسّن، وأنتج عبر الصور والفيديو والصوت والنصوص باستخدام قوة Gemini. استوديو إبداعك المتكامل في انتظارك.',
    content_type_images: 'صور',
    content_type_videos: 'فيديو',
    content_type_audio: 'صوت',
    content_type_text: 'نصوص',
    coming_soon_title: 'قريبًا!',
    coming_soon_desc: 'هذا القسم قيد التطوير. ترقبوا الميزات الجديدة والمثيرة!',
    editor_card_title: 'المحرر',
    editor_card_desc: 'حرر أجزاء من الصورة بدقة باستخدام الأقنعة والأوامر. غيّر الألوان، أضف عناصر، أو أزل العيوب.',
    start_editing: 'ابدأ التحرير',
    generator_card_title: 'المولّد',
    generator_card_desc: 'ابتكر صورًا فريدة من النصوص والصور المرجعية. خيالك هو الحد الوحيد.',
    start_generating: 'ابدأ الإنشاء',
    enhancer_card_title: 'المحسّن',
    enhancer_card_desc: 'صقل صورك وحسّن جودتها. أضف تفاصيل، أصلح العيوب، أو غيّر الأنماط بأمر بسيط.',
    start_enhancing: 'ابدأ التحسين',
    restorer_card_title: 'المرمم',
    restorer_card_desc: 'ترميم الصور القديمة وتلوينها وتحسينها مع الحفاظ على كل العناصر والتفاصيل.',
    start_restoring: 'ابدأ الترميم',
    merger_card_title: 'الدامج',
    merger_card_desc: 'اجمع عدة صور في تحفة فنية واحدة متماسكة. امزج الأساليب والمواضيع والمشاهد بسهولة.',
    start_merging: 'ابدأ الدمج',
    extractor_card_title: 'المستخرج',
    extractor_card_desc: 'استخرج النص الدقيق المستخدم لإنشاء صورة. افهم الفن وراء المرئيات.',
    start_extracting: 'ابدأ الاستخراج',
    corrector_card_title: 'المصحح',
    corrector_card_desc: 'صقل أفكارك البسيطة إلى أوامر احترافية ومفصلة للذكاء الاصطناعي. يدعم لغات متعددة.',
    start_correcting: 'ابدأ التصحيح',
    writer_card_title: 'الكاتب',
    writer_card_desc: 'أنشئ محتوى تسويقيًا ومنشورات وسائط اجتماعية والمزيد من وصف بسيط وصورة منتج اختيارية.',
    start_writing: 'ابدأ الكتابة',
    translator_card_title: 'المترجم',
    translator_card_desc: 'ترجم النصوص والمستندات بدقة عالية عبر لغات متعددة، مع ميزة الكشف التلقائي.',
    start_translating: 'ابدأ الترجمة',
    proofreader_card_title: 'المدقق اللغوي',
    proofreader_card_desc: 'تحقق من الأخطاء الإملائية والنحوية، وحسّن جودة النص، وتأكد من أن كتابتك خالية من العيوب. يدعم لغات متعددة.',
    start_proofreading: 'ابدأ التدقيق',
    stealth_card_title: 'التخفي',
    stealth_card_desc: 'أعد صياغة النصوص المولدة بالذكاء الاصطناعي لتبدو وكأنها مكتوبة بواسطة إنسان وتجنب الكشف.',
    start_stealthing: 'ابدأ التخفي',
    beta_tag: 'تجريبي',
    info_tab_about: 'عنّا',
    info_tab_why: 'لماذا نحن؟',
    info_tab_mission: 'مهمتنا',
    info_tab_features: 'المميزات',
    landing_about_title: 'عن استوديو ليان',
    landing_about_desc: 'استوديو ليان هو مركزك الإبداعي المتكامل، المدعوم بأحدث تقنيات الذكاء الاصطناعي من Gemini. نحن نقدم مجموعة متكاملة من الأدوات للصور والفيديو والصوت والنصوص، مصممة لتكون شريكك في كل مرحلة من مراحل العملية الإبداعية—من الفكرة الأولية إلى المنتج النهائي المصقول.',
    landing_importance_title: 'لماذا استوديو ليان؟',
    landing_importance_desc: 'في عالم يعتمد على المحتوى الرقمي الجذاب، أصبحت القدرة على تحويل الأفكار إلى وسائط احترافية عالية الجودة أمراً ضرورياً. استوديو ليان يزيل الحواجز التقنية، ويمكّن كل مبدع—من المحترفين إلى الهواة—من تحقيق رؤيتهم في أي وسيط بسهولة ودقة لا مثيل له.',
    landing_goals_title: 'مهمتنا',
    landing_goals_desc: 'مهمتنا هي إضفاء الطابع الديمقراطي على الإبداع من خلال وضع تقنيات الذكاء الاصطناعي متعددة الوسائط الأكثر تقدماً في متناول يديك عبر واجهة بسيطة وأنيقة. نحن نسعى لنكون الشرارة التي تلهم المبدعين لإنتاج أعمال استثنائية تترك أثراً دائماً لا يُنسى.',
    landing_features_title: 'الميزات الأساسية',
    landing_feature_1_title: 'إنشاء صور متقدم',
    landing_feature_1_desc: 'استخدم النصوص والصور لإنشاء صور عالية الدقة بأنماط ونسب أبعاد مختلفة.',
    landing_feature_2_title: 'تحسين ذكي للصور',
    landing_feature_2_desc: 'حسّن الدقة، وأضف التفاصيل، وطبّق تغييرات أسلوبية على الصور الموجودة بدقة.',
    landing_feature_3_title: 'دمج سلس للصور',
    landing_feature_3_desc: 'اجمع عناصر من ما يصل إلى 15 صورة مختلفة في تكوين واحد متناغم.',
    landing_feature_4_title: 'استخراج الأوامر النصية',
    landing_feature_4_desc: 'اكتشف الأوامر النصية وراء أي صورة، مما يوفر رؤية وإلهامًا لإبداعاتك الخاصة.',
    landing_feature_5_title: 'تحرير دقيق',
    landing_feature_5_desc: 'اعزل وعدّل أجزاء معينة من الصورة عن طريق رسم قناع، مما يوفر تحكمًا لا مثيل له في إبداعاتك.',
    landing_feature_6_title: 'تصحيح الأوامر',
    landing_feature_6_desc: 'حوّل الأفكار البسيطة إلى أوامر نصية مفصلة وعالية الجودة جاهزة للاستخدام، مع دعم متعدد اللغات.',
    landing_feature_7_title: 'ترميم ذكي للصور',
    landing_feature_7_desc: 'أصلح ولوّن وحسّن الصور القديمة أو التالفة تلقائيًا بنقرة واحدة.',
    landing_feature_8_title: 'إنشاء فيديو ديناميكي (قريبًا)',
    landing_feature_8_desc: 'أنشئ وحرر مقاطع فيديو مذهلة من الأوامر النصية أو الصور أو المقاطع الموجودة.',
    landing_feature_9_title: 'إنتاج صوتي ذكي (قريبًا)',
    landing_feature_9_desc: 'أنشئ تعليقات صوتية وموسيقى ومؤثرات صوتية عالية الجودة بأوامر بسيطة.',
    landing_feature_10_title: 'أدوات نص ومحتوى متقدمة (قريبًا)',
    landing_feature_10_desc: 'صياغة وتلخيص وترجمة محتوى مكتوب جذاب لأي غرض.',
    landing_feature_11_title: 'كاتب المحتوى',
    landing_feature_11_desc: 'أنشئ محتوى تسويقيًا ومنشورات وسائط اجتماعية والمزيد من وصف بسيط وصورة منتج اختيارية.',
    landing_feature_12_title: 'مترجم الذكاء الاصطناعي',
    landing_feature_12_desc: 'ترجم النصوص بدقة عالية عبر لغات متعددة، مع ميزة الكشف التلقائي والتحكم في الرسمية.',
    toggle_theme_dark: 'التبديل إلى الوضع الداكن',
    toggle_theme_light: 'التبديل إلى الوضع الفاتح',
    switch_language_to_ar: 'التبديل إلى اللغة العربية',
    switch_language_to_en: 'التبديل إلى اللغة الإنجليزية',
    api_key_tooltip: 'إدارة مفتاح API',
    generator_title: 'مولّد الصور',
    prompt_label: 'الأمر النصي',
    prompt_wave_tooltip: 'احصل على أمر عشوائي',
    upload_prompt_label: 'تحميل الأمر من ملف',
    paste_from_clipboard: 'لصق من الحافظة',
    paste_error_not_text: 'المحتوى الموجود في الحافظة ليس نصًا.',
    prompt_placeholder: 'مثال: لوحة سريالية لقط يعزف على التشيلو في غابة ليلًا...',
    reference_images_label: 'صور مرجعية (اختياري)',
    reference_images_desc: 'أضف ما يصل إلى 5 صور لتوجيه الإنشاء. الصيغ المدعومة: PNG, JPG, WEBP. الحجم الأقصى 10 ميجابايت لكل منها.',
    aspect_ratio_label: 'نسبة الأبعاد',
    aspect_ratio_Default: 'افتراضي',
    aspect_ratio_Square: 'مربع',
    aspect_ratio_Portrait: 'عمودي',
    aspect_ratio_Landscape: 'أفقي',
    quality_label: 'الجودة',
    quality_Standard: 'قياسية',
    quality_HD: 'عالية الدقة',
    generate_button: 'إنشاء',
    generating_title: 'جاري إنشاء الصورة...',
    generating_desc: 'الذكاء الاصطناعي يعمل بسحره. قد يستغرق هذا بعض الوقت.',
    enhancing_title: 'جاري تحسين الصورة...',
    enhancing_desc: 'تطبيق التحسينات. يجب أن يكون هذا سريعًا.',
    merging_title: 'جاري دمج الصور...',
    merging_desc: 'دمج صورك. قد يستغرق هذا بعض الوقت.',
    editing_title: 'جاري تحرير الصورة...',
    editing_desc: 'يقوم الذكاء الاصطناعي بتطبيق تعديلاتك. قد يستغرق هذا بعض الوقت.',
    restoring_title: 'جاري ترميم الصورة...',
    restoring_desc: 'يقوم الذكاء الاصطناعي بترميم صورتك بعناية. قد يستغرق هذا بعض الوقت.',
    error_title: 'حدث خطأ',
    generated_image_alt: 'نتيجة الصورة المُنشأة',
    download_image_label: 'تنزيل الصورة',
    initial_title: 'ستظهر نتيجتك هنا',
    initial_desc: 'أدخل الأمر النصي والإعدادات، ثم انقر على "إنشاء".',
    initial_desc_restorer: 'قم بتحميل صورة قديمة أو تالفة لبدء عملية الترميم.',
    initial_desc_extractor: 'قم بتحميل صورة وسيظهر النص المستخرج هنا.',
    initial_desc_corrector: 'اكتب فكرتك وسيظهر الأمر المصحح هنا.',
    initial_desc_writer: 'صف منتجك أو فكرتك لإنشاء المحتوى.',
    initial_desc_translator: 'أدخل نصًا، اختر اللغات، وستظهر الترجمة هنا.',
    initial_desc_proofreader: 'أدخل النص الخاص بك وستظهر النسخة المصححة هنا.',
    initial_desc_stealth: 'أدخل النص المولد بالذكاء الاصطناعي وستظهر النسخة المؤنسنة هنا.',
    enhancer_title: 'محسّن الصور',
    restorer_title: 'مرمم الصور',
    base_image_label: 'الصورة الأساسية',
    base_image_desc: 'قم بتحميل صورة واحدة لتحسينها. الصيغ المدعومة: PNG, JPG, WEBP.',
    base_image_desc_editor: 'قم بتحميل صورة واحدة لتحريرها. الصيغ المدعومة: PNG, JPG, WEBP.',
    base_image_desc_restorer: 'قم بتحميل صورة واحدة قديمة أو تالفة لترميمها. الصيغ المدعومة: PNG, JPG, WEBP.',
    restorer_options_label: 'خيارات الترميم',
    restorer_advanced_options_toggle: 'خيارات متقدمة',
    restorer_option_fix_damage: 'إصلاح الخدوش والتمزقات',
    restorer_option_improve_clarity: 'تحسين الوضوح',
    restorer_option_colorize: 'تلوين الصورة',
    restorer_option_remove_noise: 'إزالة التشويش (التحبب)',
    restorer_instructions_label: 'تعليمات إضافية (اختياري)',
    restorer_instructions_placeholder: 'مثال: التركيز على ترميم الوجوه، جعل السماء زرقاء...',
    enhancement_label: 'أمر التحسين',
    enhancement_placeholder: 'مثال: زيادة الدقة، إضافة إضاءة سينمائية، جعلها تبدو كلوحة زيتية...',
    enhancement_strength: 'قوة التحسين',
    enhance_button: 'تحسين',
    restore_button: 'ترميم',
    editor_title: 'محرر الصور',
    edit_instructions_label: 'تعليمات التحرير العامة',
    edit_instructions_placeholder: 'مثال: اجعل الصورة العامة تبدو سينمائية أكثر، أضف تركيزًا ناعمًا...',
    color_prompt_placeholder: 'مثال: حول هذا الجزء إلى طوب أحمر',
    mask_area_label: 'منطقة التحرير',
    mask_area_desc: 'استخدم الفرشاة للرسم فوق أجزاء الصورة التي تريد تغييرها.',
    brush_size: 'حجم الفرشاة',
    mask_color: 'لون القناع',
    clear_mask: 'مسح القناع',
    undo_mask: 'التراجع عن آخر خطوة',
    redo_mask: 'الإعادة',
    edit_button: 'تحرير الصورة',
    reset_view: 'إعادة ضبط العرض',
    tool_brush: 'فرشاة',
    tool_eraser: 'ممحاة',
    tool_pan: 'أداة التحريك',
    toggle_mask_visibility: 'إظهار/إخفاء القناع',
    editor_pan_instruction: 'استخدم عجلة الماوس للتكبير، اضغط باستمرار على Space واسحب للتحريك.',
    zoom_tool: 'أداة التكبير',
    allow_shrinking: 'السماح بالتقليص',
    allow_zooming: 'السماح بالتكبير',
    extractor_title: 'مستخرج الأوامر',
    base_image_label_extractor: 'صورة لاستخراج النص منها',
    base_image_desc_extractor: 'قم بتحميل الصورة التي تريد تحليلها.',
    extraction_mode_label: 'وضع الاستخراج',
    extraction_mode_descriptive: 'وصفي',
    extraction_mode_concise: 'موجز',
    output_language_label: 'لغة الإخراج',
    output_language_auto: 'كشف تلقائي',
    output_language_en: 'الإنجليزية',
    output_language_ar: 'العربية',
    output_language_es: 'الإسبانية',
    output_language_fr: 'الفرنسية',
    output_language_de: 'الألمانية',
    output_language_ja: 'اليابانية',
    output_language_zh: 'الصينية',
    output_language_ru: 'الروسية',
    output_language_hi: 'الهندية',
    extract_button: 'استخراج الأمر',
    extracting_title: 'جاري استخراج الأمر...',
    extracting_desc: 'تحليل الصورة للكشف عن الأمر النصي الخاص بها.',
    corrector_title: 'مصحح الأوامر',
    corrector_idea_label: 'فكرتك',
    corrector_idea_placeholder: 'مثال: فارس يقاتل تنينًا في كهف بلوري',
    correct_button: 'تصحيح الأمر',
    correcting_title: 'جاري تصحيح الأمر...',
    correcting_desc: 'الذكاء الاصطناعي يصقل فكرتك ليحولها إلى أمر فني.',
    writer_title: 'كاتب المحتوى',
    writer_idea_label: 'الفكرة أو وصف المنتج',
    writer_idea_placeholder: 'مثال: علامة تجارية جديدة للقهوة العضوية، من إثيوبيا، ذات نكهة ناعمة وغنية.',
    writer_optional_image_label: 'صورة المنتج (اختياري)',
    writer_optional_image_desc: 'أضف ما يصل إلى 5 صور منتجات لتوجيه إنشاء المحتوى.',
    writer_advanced_options_toggle: 'خيارات متقدمة',
    writer_ratio_label: 'نسبة المحتوى',
    writer_tone_label: 'نبرة المحتوى',
    tone_professional: 'احترافي',
    tone_casual: 'غير رسمي',
    tone_enthusiastic: 'حماسي',
    tone_humorous: 'فكاهي',
    tone_academic: 'أكاديمي',
    tone_creative: 'إبداعي',
    writer_content_type_label: 'نوع المحتوى',
    content_type_social_media: 'منشور تواصل اجتماعي',
    content_type_product_desc: 'وصف منتج',
    content_type_blog_idea: 'فكرة مقال',
    content_type_email: 'بريد تسويقي',
    generate_content_button: 'إنشاء المحتوى',
    writing_title: 'جاري كتابة المحتوى...',
    writing_desc: 'الذكاء الاصطناعي يصوغ المحتوى الخاص بك. قد يستغرق هذا بعض الوقت.',
    translator_title: 'مترجم النصوص',
    translator_input_label: 'النص أو الملف المراد ترجمته',
    translator_input_placeholder: 'أدخل النص هنا أو قم بتحميل ملف...',
    translator_file_uploaded_label: 'ملف للترجمة:',
    translator_remove_file_tooltip: 'إزالة الملف',
    translator_output_format_note: 'ملاحظة: سيتم توفير المحتوى المترجم من الملفات كنص عادي.',
    translator_from_label: 'من',
    translator_to_label: 'إلى',
    swap_languages_tooltip: 'تبديل اللغات',
    translator_advanced_options_toggle: 'خيارات متقدمة',
    translator_accuracy_label: 'دقة الترجمة',
    formality_label: 'الرسمية',
    formality_default: 'افتراضي',
    formality_formal: 'رسمي',
    formality_informal: 'غير رسمي',
    translate_button: 'ترجمة',
    translating_title: 'جاري الترجمة...',
    translating_desc: 'الذكاء الاصطناعي يترجم المحتوى. يرجى الانتظار.',
    proofreader_title: 'المدقق اللغوي',
    proofreader_input_label: 'النص أو الملف المطلوب تدقيقه',
    proofreader_input_placeholder: 'أدخل النص هنا أو قم بتحميل ملف...',
    proofreader_file_uploaded_label: 'ملف للتدقيق:',
    proofreader_remove_file_tooltip: 'إزالة الملف',
    proofreader_output_format_note: 'ملاحظة: سيتم توفير المحتوى المصحح من الملفات كنص عادي.',
    proofread_button: 'تدقيق',
    proofreading_title: 'جاري تدقيق النص...',
    proofreading_desc: 'يقوم الذكاء الاصطناعي بفحص النص بحثًا عن الأخطاء والتحسينات.',
    proofreader_advanced_options_toggle: 'خيارات متقدمة',
    correction_level_label: 'مستوى التصحيح',
    correction_level_basic: 'أساسي',
    correction_level_advanced: 'متقدم',
    correction_level_rewrite: 'إعادة صياغة',
    target_audience_label: 'الجمهور المستهدف',
    audience_general: 'عام',
    audience_academic: 'أكاديمي',
    audience_business: 'أعمال',
    proofreader_vocalization_label: 'التشكيل اللغوي',
    proofreader_grammar_discipline_label: 'الانضباط بقواعد اللغة',
    stealth_title: 'التخفي',
    stealth_input_label: 'النص المولد بالذكاء الاصطناعي',
    stealth_input_placeholder: 'الصق النص المولد بالذكاء الاصطناعي هنا...',
    stealth_advanced_options_toggle: 'خيارات متقدمة',
    stealth_file_uploaded_label: 'ملف للأنسنة:',
    stealth_remove_file_tooltip: 'إزالة الملف',
    stealth_output_format_note: 'ملاحظة: سيتم توفير المحتوى المؤنسن من الملفات كنص عادي.',
    rewrite_intensity_label: 'شدة إعادة الصياغة',
    humanization_tone_label: 'نبرة التخفي',
    complexity_level_label: 'مستوى التعقيد',
    complexity_simple: 'بسيط',
    complexity_standard: 'قياسي',
    complexity_advanced: 'متقدم',
    humanization_techniques_label: 'تقنيات الأنسنة',
    technique_anecdotes: 'إضافة حكايات/تعابير شخصية',
    technique_vary_structure: 'تنويع بنية الجمل',
    technique_imperfections: 'إضافة عيوب طفيفة',
    stealth_button: 'أنسنة النص',
    stealthing_title: 'جاري أنسنة النص...',
    stealthing_desc: 'يعمل الذكاء الاصطناعي بسحره لجعل النص يبدو أكثر إنسانية.',
    copy_success: 'تم النسخ!',
    copy_button: 'نسخ إلى الحافظة',
    download_prompt_label: 'تنزيل كملف .txt',
    image_preview_title: 'معاينة الصورة',
    close_preview: 'إغلاق المعاينة',
    uploader_cta_title: 'تحميل الصور',
    uploader_cta_desc: 'انقر للتحميل أو اسحب وأفلت. ملف واحد أو عدة ملفات.',
    uploader_cta_desc_translator: 'تحميل ملف .txt, .pdf, أو .docx',
    uploader_cta_desc_stealth: 'تحميل ملف .txt, .pdf, أو .docx',
    uploader_cta_add_more: 'إضافة المزيد',
    uploader_error_size: 'الملف كبير جدًا. الحجم الأقصى هو 10 ميجابايت.',
    uploader_error_type: 'نوع ملف غير صالح. يرجى استخدام PNG أو JPG أو WEBP.',
    uploader_error_count: 'يمكنك تحميل 5 صور كحد أقصى.',
    uploader_error_single_count: 'يمكنك تحميل صورة واحدة فقط.',
    uploader_error_merge_count: 'يمكنك تحميل 15 صورة كحد أقصى للدمج.',
    merger_title: 'دامج الصور',
    source_images_label: 'الصور المصدر',
    source_images_desc: 'قم بتحميل من 2 إلى 15 صورة لدمجها.',
    merger_prompt_label: 'تعليمات الدمج (اختياري)',
    merger_prompt_placeholder: 'مثال: ادمج هذه الصور في مشهد خيالي. استخدم القلعة من الصورة 1 والتنين من الصورة 2...',
    merge_button: 'دمج',
    api_key_modal_title_manual: 'مفتاح Gemini API الخاص بك',
    api_key_modal_desc_manual: 'يتم تخزين مفتاحك بشكل آمن في التخزين المحلي للمتصفح ولا يتم إرساله أبدًا إلى خوادمنا. يتيح لك هذا استخدام النماذج والحصص الخاصة بك.',
    api_key_input_placeholder: 'أدخل مفتاح Gemini API الخاص بك',
    api_key_save_button: 'حفظ المفتاح',
    api_key_close_button: 'إغلاق',
    show_api_key: 'إظهار مفتاح API',
    hide_api_key: 'إخفاء مفتاح API',
    api_key_validating: 'جاري التحقق...',
    api_key_valid: 'المفتاح صالح',
    api_key_invalid: 'مفتاح API غير صالح',
    footer_text: 'صُنع بكل حب',
    footer_copyright_brand: '© {year} Google\'s Gemini AI',
    footer_copyright_legal: 'جميع الحقوق محفوظة.',
    contact_us_tooltip: 'تواصل بنا',
    developer_modal_title: 'حول المطور',
    developer_label: 'المطور',
    developer_name: 'صلاح الدين منصور الدروبي',
    developer_bio: 'مطور ومصمم جرافيك، يجمع بين الشغف بالبرمجة والخبرة في التصميم لإنشاء تجارب رقمية مبتكرة وجميلة.',
    tooltip_facebook: 'فيسبوك',
    tooltip_instagram: 'انستغرام',
    tooltip_x: 'إكس (تويتر)',
    tooltip_telegram: 'تلغرام',
    tooltip_whatsapp: 'واتساب',
    tooltip_email: 'بريد إلكتروني',
    tooltip_github: 'جيت هاب',
    collapse_toolbar: 'طي شريط الأدوات',
    expand_toolbar: 'توسيع شريط الأدوات',
    prompts_label: 'برومت',
    prompts_available_tooltip: '+{count} برومت متاح',
  },
};

export type Language = 'en' | 'ar';
export type TFunction = (key: keyof typeof translations.en) => string;
type Direction = 'ltr' | 'rtl';

export const useLocalization = () => {
  const [language, setLanguage] = useState<Language>('ar');

  const setLang = useCallback((lang: Language) => {
    setLanguage(lang);
  }, []);

  const t = useCallback((key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key];
  }, [language]);
  
  const dir: Direction = language === 'ar' ? 'rtl' : 'ltr';

  return { t, setLanguage: setLang, language, dir };
};
